### ISSUE TITLE
Cannot set property 'parent' of undefined

### ISSUE THREAD

**Issue by in-in** [solversgroup/postcss-sort-media-queries#33]
I use Next.js and the plugin does not work with it properly.

After the `next dev` command I get an error:
```sh
error - ./components/footer/styles.module.css ((webpack)/css-loader/cjs.js??ref--5-oneOf-2-1!(webpack)/postcss-loader/cjs.js??ref--5-oneOf-2-2!./components/footer/styles.module.css)
TypeError: Cannot set property 'parent' of undefined
```

```js
// postcss.config.js
module.exports = {
	plugins: {
		'autoprefixer': {},
		'postcss-flexbugs-fixes': {},
		'postcss-media-minmax': {},
		'postcss-nested': {},
		'postcss-sort-media-queries': {}
	}
}
```

```js
// next.config.js
module.exports = {
	distDir: 'build',
	poweredByHeader: false,
	reactStrictMode: true
}
```

```css
/* ./components/footer/styles.module.css */
.footer {
	grid-area: footer;
	background-color: green;

	@media (width >= 600px) {
		background-color: pink;
	}
}

```
package.json
```json
	"dependencies": {
		"next": "10.1.3",
		"react": "17.0.2",
		"react-dom": "17.0.2"
	},
	"devDependencies": {
		"autoprefixer": "10.2.5",
		"postcss": "8.2.10",
		"postcss-flexbugs-fixes": "5.0.2",
		"postcss-media-minmax": "5.0.0",
		"postcss-nested": "5.0.5",
		"postcss-sort-media-queries": "3.8.9"
	}
```

**Comment by yunusga** [comment]
Hi @in-in. Can you show before after CSS?

**Comment by in-in** [comment]
I showed before CSS in the question (see the footer component above), but I do not have after CSS so the project can not build

**Comment by yunusga** [comment]
I create two test for this case, and all works fine

```bash
√ postcss media minmax -> nested (4 ms)
√ postcss nested -> media minmax (2 ms)
```

```js
// mediaMinmaxBeforeNestedRun
postcss([autoprefixer, flexbugsFixes, mediaMinMax, nested, plugin(opts)]).process(input, { from: undefined })

// mediaMinmaxAfterNestedRun
postcss([autoprefixer, flexbugsFixes, nested, mediaMinMax, plugin(opts)]).process(input, { from: undefined })
```

### Before

```css
.footer {
    grid-area: footer;
    background-color: green;

    @media (width >= 600px) {
        background-color: pink;
    }

    .footer-content {
        grid-area: footer-content;

        @media (width >= 990px) {
            background-color: aliceblue;
        }
    }
}
```

### After

```css
.footer {
    grid-area: footer;
    background-color: green;
}

.footer .footer-content {
    grid-area: footer-content;
}

@media (min-width: 600px) {
    .footer {
        background-color: pink
    }
}
@media (min-width: 990px) {
    .footer .footer-content {
        background-color: aliceblue
    }
}
```
